import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:dio/dio.dart';
import 'package:talker_dio_logger/talker_dio_logger.dart';

import '../../constants/endpoints.dart';

final dioProvider = Provider<Dio>((ref) {
  final dio = Dio();
  final _refreshToken = 'refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsZXZlbCI6IiIsInBlcm1pc3Npb25zIjpudWxsLCJ1c2VyX25hbWUiOiIiLCJzaXRlX25hbWUiOiIiLCJleHAiOjE3Mzk0NjQ5MjQsImlzcyI6IjEyMzQ1In0.2t1b7B9jMOqbpYxTqml5xQ9cpXo5nlCBySr_rOstbzc; token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsZXZlbCI6IjEiLCJwZXJtaXNzaW9ucyI6eyIxIjp0cnVlLCIxMCI6dHJ1ZSwiMTAwIjp0cnVlLCIxMDEiOnRydWUsIjEwMiI6dHJ1ZSwiMTAzIjp0cnVlLCIxMDQiOnRydWUsIjEwNSI6dHJ1ZSwiMTA2Ijp0cnVlLCIxMDciOnRydWUsIjEwOCI6dHJ1ZSwiMTA5Ijp0cnVlLCIxMSI6dHJ1ZSwiMTEwIjp0cnVlLCIxMTEiOnRydWUsIjExMiI6dHJ1ZSwiMTEzIjp0cnVlLCIxMTQiOnRydWUsIjExNSI6dHJ1ZSwiMTE2Ijp0cnVlLCIxMTciOnRydWUsIjExOCI6dHJ1ZSwiMTE5Ijp0cnVlLCIxMiI6dHJ1ZSwiMTIwIjp0cnVlLCIxMjEiOnRydWUsIjEyMiI6dHJ1ZSwiMTIzIjp0cnVlLCIxMjQiOnRydWUsIjEyNSI6dHJ1ZSwiMTI2Ijp0cnVlLCIxMjciOnRydWUsIjEyOCI6dHJ1ZSwiMTI5Ijp0cnVlLCIxMyI6dHJ1ZSwiMTMwIjp0cnVlLCIxMzEiOnRydWUsIjEzMiI6dHJ1ZSwiMTMzIjp0cnVlLCIxMzQiOnRydWUsIjEzNSI6dHJ1ZSwiMTM2Ijp0cnVlLCIxMzciOnRydWUsIjEzOCI6dHJ1ZSwiMTM5Ijp0cnVlLCIxNCI6dHJ1ZSwiMTQwIjp0cnVlLCIxNDEiOnRydWUsIjE0MiI6dHJ1ZSwiMTQzIjp0cnVlLCIxNDQiOnRydWUsIjE0NSI6dHJ1ZSwiMTQ2Ijp0cnVlLCIxNDciOnRydWUsIjE0OCI6dHJ1ZSwiMTQ5Ijp0cnVlLCIxNSI6dHJ1ZSwiMTUwIjp0cnVlLCIxNTEiOnRydWUsIjE1MiI6dHJ1ZSwiMTUzIjp0cnVlLCIxNTQiOnRydWUsIjE1NSI6dHJ1ZSwiMTU3Ijp0cnVlLCIxNTgiOnRydWUsIjE1OSI6dHJ1ZSwiMTYiOnRydWUsIjE2MCI6dHJ1ZSwiMTYxIjp0cnVlLCIxNjIiOnRydWUsIjE2MyI6dHJ1ZSwiMTY0Ijp0cnVlLCIxNjUiOnRydWUsIjE2NiI6dHJ1ZSwiMTY3Ijp0cnVlLCIxNjgiOnRydWUsIjE2OSI6dHJ1ZSwiMTciOnRydWUsIjE3MSI6dHJ1ZSwiMTcyIjp0cnVlLCIxNzMiOnRydWUsIjE3NCI6dHJ1ZSwiMTc1Ijp0cnVlLCIxNzYiOnRydWUsIjE4Ijp0cnVlLCIxOSI6dHJ1ZSwiMiI6dHJ1ZSwiMjAiOnRydWUsIjIxIjp0cnVlLCIyMiI6dHJ1ZSwiMjMiOnRydWUsIjI0Ijp0cnVlLCIyNSI6dHJ1ZSwiMjYiOnRydWUsIjI3Ijp0cnVlLCIyOCI6dHJ1ZSwiMjkiOnRydWUsIjMiOnRydWUsIjMwIjp0cnVlLCIzMSI6dHJ1ZSwiMzIiOnRydWUsIjMzIjp0cnVlLCIzNCI6dHJ1ZSwiMzUiOnRydWUsIjM2Ijp0cnVlLCIzOCI6dHJ1ZSwiMzkiOnRydWUsIjQiOnRydWUsIjQwIjp0cnVlLCI0MSI6dHJ1ZSwiNDQiOnRydWUsIjQ1Ijp0cnVlLCI0NiI6dHJ1ZSwiNDciOnRydWUsIjQ4Ijp0cnVlLCI0OSI6dHJ1ZSwiNSI6dHJ1ZSwiNTAiOnRydWUsIjUxIjp0cnVlLCI1MiI6dHJ1ZSwiNTMiOnRydWUsIjU0Ijp0cnVlLCI1NSI6dHJ1ZSwiNTYiOnRydWUsIjU3Ijp0cnVlLCI1OCI6dHJ1ZSwiNTkiOnRydWUsIjYiOnRydWUsIjYwIjp0cnVlLCI2MSI6dHJ1ZSwiNjIiOnRydWUsIjYzIjp0cnVlLCI2NCI6dHJ1ZSwiNjYiOnRydWUsIjY3Ijp0cnVlLCI2OCI6dHJ1ZSwiNjkiOnRydWUsIjciOnRydWUsIjcwIjp0cnVlLCI3MiI6dHJ1ZSwiNzMiOnRydWUsIjc0Ijp0cnVlLCI3NSI6dHJ1ZSwiNzYiOnRydWUsIjc3Ijp0cnVlLCI3OCI6dHJ1ZSwiOCI6dHJ1ZSwiODAiOnRydWUsIjgxIjp0cnVlLCI4MiI6dHJ1ZSwiODMiOnRydWUsIjg0Ijp0cnVlLCI4NSI6dHJ1ZSwiODYiOnRydWUsIjg3Ijp0cnVlLCI4OCI6dHJ1ZSwiODkiOnRydWUsIjkiOnRydWUsIjkwIjp0cnVlLCI5MSI6dHJ1ZSwiOTIiOnRydWUsIjkzIjp0cnVlLCI5NCI6dHJ1ZSwiOTUiOnRydWUsIjk2Ijp0cnVlLCI5NyI6dHJ1ZSwiOTgiOnRydWUsIjk5Ijp0cnVlfSwidXNlcl9uYW1lIjoiQWRtaW5pc3RyYXRvciIsInNpdGVfbmFtZSI6IkhlYWQgT2ZmaWNlIEpha2FydGEiLCJleHAiOjE3MzY5NTkzMjQsImlzcyI6IjEyMzQ1In0.k-_iw_TS3o3pZKmih5ZvmnmW_chwCdgFLjr78zrIxbs';

  dio.options
    ..baseUrl = Endpoints.baseUrl
    ..headers = {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    }
    ..connectTimeout = const Duration(milliseconds: Endpoints.connectionTimeout)
    ..receiveTimeout = const Duration(milliseconds: Endpoints.receiveTimeout);

  dio.interceptors.add(
    TalkerDioLogger(
      settings: const TalkerDioLoggerSettings(
        printRequestHeaders: true,
        printResponseMessage: true,
      ),
    ),
  );

  dio.interceptors.add(
    InterceptorsWrapper(
      onRequest: (options, handler) async {
        options.headers['Cookie'] = '$_refreshToken';
        return handler.next(options);
      },
    ),
  );

  return dio;
});
